import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import DashboardSidebar from "./_components/sidebar";
import Navbar from "./_components/navbar";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-full flex">
      <DashboardSidebar />

      <div className="w-full h-full">
        <Navbar />
        {children}
      </div>
    </main>
  );
}
