import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Authenticated } from "convex/react";
import { Flowbite } from "flowbite-react";
import { Toaster } from "@/components/ui/sonner";
import ProgressBarProviders from "@/providers/progress-bar-provider";
import RouteChangeListener from "./board/_components/routeChangeListener";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite>
          <ProgressBarProviders>
            <ConvexClientProvider>
              {children}
              <RouteChangeListener />
            </ConvexClientProvider>
          </ProgressBarProviders>
        </Flowbite>
        <Toaster className="z-50" />
      </body>
    </html>
  );
}
